version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Compile
          command: yarn compile
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test with Coverage
          command: yarn coverage
      - run:
          name: Report code coverage
          command: yarn report-coverage
